version: '3'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - PORT=5000
    depends_on:
      - simple
      - splade

  simple:
    build:
      context: ./simple_embeddings
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./simple_embeddings:/app
    environment:
      - PORT=5001

  splade:
    build:
      context: ./SPLADE
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./SPLADE:/app
    environment:
      - PORT=5002