version: '3'

services:
  splade-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production